R"(#"

set(SOURCES ${%SOURCES%})
set(OUT_NAME ${%OUT_NAME%})
set(OUT_DIR ${%OUT_DIR%})
set(UNIQUE ${%UNIQUE%})
set(TEST_MAIN_FILES ${%TEST_MAIN_FILES%})
set(TEST_OUT_DIR ${%TEST_OUT_DIR%})
set(DEPS ${%DEPS%})
set(INC ${%INC%})

${%FOR_GEN%}
${%FOR_MODE%}
${%FOR_TEST%}

set(INCLUDE_DIRS ${M_INCLUDE_DIRS} ${MODE_INCLUDE_DIRS} ${GEN_INCLUDE_DIRS} ${GEN_MODE_INCLUDE_DIRS} ${INC})
set(LIB_DIRS ${M_LIB_DIRS} ${MODE_LIB_DIRS} ${GEN_LIB_DIRS} ${GEN_MODE_LIB_DIRS})
set(LIBS ${M_LIBS} ${MODE_LIBS} ${GEN_LIBS} ${GEN_MODE_LIBS} ${DEPS})
set(DEFINES ${M_DEFINES} ${MODE_DEFINES} ${GEN_DEFINES} ${GEN_MODE_DEFINES})
set(COPTIONS ${M_COPTIONS} ${MODE_COPTIONS} ${GEN_COPTIONS} ${GEN_MODE_COPTIONS})
set(LINKOPTIONS ${M_LINKOPTIONS} ${MODE_LINKOPTIONS} ${GEN_LINKOPTIONS} ${GEN_MODE_LINKOPTIONS})
set(UNIQUE_NAME "${OUT_NAME}_${UNIQUE}")

add_library(${UNIQUE_NAME} MODULE ${SOURCES})
target_include_directories(${UNIQUE_NAME} PRIVATE ${INCLUDE_DIRS})
target_link_directories(${UNIQUE_NAME} PRIVATE ${LIB_DIRS})
target_link_libraries(${UNIQUE_NAME} PRIVATE ${LIBS})
target_compile_definitions(${UNIQUE_NAME} PRIVATE ${DEFINES})
target_compile_options(${UNIQUE_NAME} PRIVATE ${COPTIONS})
target_link_options(${UNIQUE_NAME} PRIVATE ${LINKOPTIONS})
set_target_properties(${UNIQUE_NAME} PROPERTIES
    OUTPUT_NAME ${OUT_NAME}
    PREFIX ""
    RUNTIME_OUTPUT_DIRECTORY ${OUT_DIR})

foreach(TEST_MAIN_FILE ${TEST_MAIN_FILES})
    get_filename_component(TEST_NAME ${TEST_MAIN_FILE} NAME_WLE)
    set(TEST_UNIQUE_NAME "test_${TEST_NAME}_${UNIQUE}")
    add_executable(${TEST_UNIQUE_NAME} ${SOURCES} ${TEST_MAIN_FILE})
    target_include_directories(${TEST_UNIQUE_NAME} PRIVATE ${INCLUDE_DIRS} ${TEST_INCLUDE_DIRS} ${TEST_MODE_INCLUDE_DIRS})
    target_link_directories(${TEST_UNIQUE_NAME} PRIVATE ${LIB_DIRS} ${TEST_LIB_DIRS} ${TEST_MODE_LIB_DIRS})
    target_link_libraries(${TEST_UNIQUE_NAME} PRIVATE ${LIBS} ${TEST_LIBS} ${TEST_MODE_LIBS})
    target_compile_definitions(${TEST_UNIQUE_NAME} PRIVATE ${DEFINES} ${TEST_DEFINES} ${TEST_MODE_DEFINES})
    target_compile_options(${TEST_UNIQUE_NAME} PRIVATE ${COPTIONS} ${TEST_COPTIONS} ${TEST_MODE_COPTIONS})
    target_link_options(${TEST_UNIQUE_NAME} PRIVATE ${LINKOPTIONS} ${TEST_LINKOPTIONS} ${TEST_MODE_LINKOPTIONS})
    set_target_properties(${TEST_UNIQUE_NAME} PROPERTIES
        OUTPUT_NAME ${TEST_NAME}
        PREFIX ""
        RUNTIME_OUTPUT_DIRECTORY ${TEST_OUT_DIR})
endforeach(TEST_MAIN_FILE ${TEST_MAIN_FILES})

#)"