name = "cup"
version = "1.2.2"
license = "GPL-2.0"

[build]
stdcxx = 20
target = "binary"
jobs = 0
# generator = "MinGW Makefiles"

[dependencies]
tomlpp = { git = "@Anglebase/tomlpp", version = "0.1.0" }
