name = "cup"
version = "1.3.0"
license = "GPL-2.0"

[build]
stdcxx = 20
target = "binary"
jobs = 0
# generator = "MinGW Makefiles"

[dependencies]
tomlpp = { git = "@Anglebase/tomlpp", version = "3.4.0" }
