[project]
name = "cup"
type = "binary"
version = "2.0.0"

[build]
jobs = 0
stdcxx = 20
defines = ["_VER_X=2", "_VER_Y=0", "_VER_Z=0"]

[dependencies]
tomlpp = { url = "@Anglebase/tomlpp", version = "3.4.0" }
