R"(#"
if(${CMAKE_GENERATOR} STREQUAL ${%GEN%})
    set(GEN_INCLUDE_DIRS ${%GEN_INCLUDE_DIRS%})
    set(GEN_LIB_DIRS ${%GEN_LIB_DIRS%})
    set(GEN_LIBS ${%GEN_LIBS%})
    set(GEN_DEFINES ${%GEN_DEFINES%})
    set(GEN_COPTIONS ${%GEN_COPTIONS%})
    set(GEN_LINKOPTIONS ${%GEN_LINKOPTIONS%})

    if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
        # Debug
        set(GEN_MODE_INCLUDE_DIRS ${%GEN_DEBUG_INCLUDE_DIRS%})
        set(GEN_MODE_LIB_DIRS ${%GEN_DEBUG_LIB_DIRS%})
        set(GEN_MODE_LIBS ${%GEN_DEBUG_LIBS%})
        set(GEN_MODE_DEFINES ${%GEN_DEBUG_DEFINES%})
        set(GEN_MODE_COPTIONS ${%GEN_DEBUG_COPTIONS%})
        set(GEN_MODE_LINKOPTIONS ${%GEN_DEBUG_LINKOPTIONS%})
    else()
        # Release
        set(GEN_MODE_INCLUDE_DIRS ${%GEN_RELEASE_INCLUDE_DIRS%})
        set(GEN_MODE_LIB_DIRS ${%GEN_RELEASE_LIB_DIRS%})
        set(GEN_MODE_LIBS ${%GEN_RELEASE_LIBS%})
        set(GEN_MODE_DEFINES ${%GEN_RELEASE_DEFINES%})
        set(GEN_MODE_COPTIONS ${%GEN_RELEASE_COPTIONS%})
        set(GEN_MODE_LINKOPTIONS ${%GEN_RELEASE_LINKOPTIONS%})
    endif()
endif()
#)"