R"(#"
set(FEAT_${%UNIQUE%}_INCLUDE_DIRS ${%FEAT_INCLUDE_DIRS%})
set(FEAT_${%UNIQUE%}_LIB_DIRS ${%FEAT_LIB_DIRS%})
set(FEAT_${%UNIQUE%}_LIBS ${%FEAT_LIBS%})
set(FEAT_${%UNIQUE%}_DEFINES ${%FEAT_DEFINES%})
set(FEAT_${%UNIQUE%}_COPTIONS ${%FEAT_COPTIONS%})
set(FEAT_${%UNIQUE%}_LINKOPTIONS ${%FEAT_LINKOPTIONS%})

if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    # Debug
    set(FEAT_${%UNIQUE%}_MODE_INCLUDE_DIRS ${%FEAT_DEBUG_INCLUDE_DIRS%})
    set(FEAT_${%UNIQUE%}_MODE_LIB_DIRS ${%FEAT_DEBUG_LIB_DIRS%})
    set(FEAT_${%UNIQUE%}_MODE_LIBS ${%FEAT_DEBUG_LIBS%})
    set(FEAT_${%UNIQUE%}_MODE_DEFINES ${%FEAT_DEBUG_DEFINES%})
    set(FEAT_${%UNIQUE%}_MODE_COPTIONS ${%FEAT_DEBUG_COPTIONS%})
    set(FEAT_${%UNIQUE%}_MODE_LINKOPTIONS ${%FEAT_DEBUG_LINKOPTIONS%})
else()
    # Release
    set(FEAT_${%UNIQUE%}_MODE_INCLUDE_DIRS ${%FEAT_RELEASE_INCLUDE_DIRS%})
    set(FEAT_${%UNIQUE%}_MODE_LIB_DIRS ${%FEAT_RELEASE_LIB_DIRS%})
    set(FEAT_${%UNIQUE%}_MODE_LIBS ${%FEAT_RELEASE_LIBS%})
    set(FEAT_${%UNIQUE%}_MODE_DEFINES ${%FEAT_RELEASE_DEFINES%})
    set(FEAT_${%UNIQUE%}_MODE_COPTIONS ${%FEAT_RELEASE_COPTIONS%})
    set(FEAT_${%UNIQUE%}_MODE_LINKOPTIONS ${%FEAT_RELEASE_LINKOPTIONS%})
endif()
#)"