R"(#"
set(FEAT_INCLUDE_DIRS ${%FEAT_INCLUDE_DIRS%})
set(FEAT_LIB_DIRS ${%FEAT_LIB_DIRS%})
set(FEAT_LIBS ${%FEAT_LIBS%})
set(FEAT_DEFINES ${%FEAT_DEFINES%})
set(FEAT_COPTIONS ${%FEAT_COPTIONS%})
set(FEAT_LINKOPTIONS ${%FEAT_LINKOPTIONS%})
#)"