R"(#"

set(M_INCLUDE_DIRS ${%MODE_INCLUDE_DIRS%})
set(M_LIB_DIRS ${%MODE_LIB_DIRS%})
set(M_LIBS ${%MODE_LIBS%})
set(M_DEFINES ${%MODE_DEFINES%})
set(M_COPTIONS ${%MODE_COPTIONS%})
set(M_LINKOPTIONS ${%MODE_LINKOPTIONS%})

if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    set(MODE_INCLUDE_DIRS ${%MODE_DEBUG_INCLUDE_DIRS%})
    set(MODE_LIB_DIRS ${%MODE_DEBUG_LIB_DIRS%})
    set(MODE_LIBS ${%MODE_DEBUG_LIBS%})
    set(MODE_DEFINES ${%MODE_DEBUG_DEFINES%})
    set(MODE_COPTIONS ${%MODE_DEBUG_COPTIONS%})
    set(MODE_LINKOPTIONS ${%MODE_DEBUG_LINKOPTIONS%})
else()
    set(MODE_INCLUDE_DIRS ${%MODE_RELEASE_INCLUDE_DIRS%})
    set(MODE_LIB_DIRS ${%MODE_RELEASE_LIB_DIRS%})
    set(MODE_LIBS ${%MODE_RELEASE_LIBS%})
    set(MODE_DEFINES ${%MODE_RELEASE_DEFINES%})
    set(MODE_COPTIONS ${%MODE_RELEASE_COPTIONS%})
    set(MODE_LINKOPTIONS ${%MODE_RELEASE_LINKOPTIONS%})
endif()

#)"