R"(#"
if(${CMAKE_SYSTEM_NAME} STREQUAL ${%TARGET%})
    set(TARGET_INCLUDE_DIRS ${%TARGET_INCLUDE_DIRS%})
    set(TARGET_LIB_DIRS ${%TARGET_LIB_DIRS%})
    set(TARGET_LIBS ${%TARGET_LIBS%})
    set(TARGET_DEFINES ${%TARGET_DEFINES%})
    set(TARGET_COPTIONS ${%TARGET_COPTIONS%})
    set(TARGET_LINKOPTIONS ${%TARGET_LINKOPTIONS%})

    if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
        # Debug
        set(TARGET_MODE_INCLUDE_DIRS ${%TARGET_DEBUG_INCLUDE_DIRS%})
        set(TARGET_MODE_LIB_DIRS ${%TARGET_DEBUG_LIB_DIRS%})
        set(TARGET_MODE_LIBS ${%TARGET_DEBUG_LIBS%})
        set(TARGET_MODE_DEFINES ${%TARGET_DEBUG_DEFINES%})
        set(TARGET_MODE_COPTIONS ${%TARGET_DEBUG_COPTIONS%})
        set(TARGET_MODE_LINKOPTIONS ${%TARGET_DEBUG_LINKOPTIONS%})
    else()
        # Release
        set(TARGET_MODE_INCLUDE_DIRS ${%TARGET_RELEASE_INCLUDE_DIRS%})
        set(TARGET_MODE_LIB_DIRS ${%TARGET_RELEASE_LIB_DIRS%})
        set(TARGET_MODE_LIBS ${%TARGET_RELEASE_LIBS%})
        set(TARGET_MODE_DEFINES ${%TARGET_RELEASE_DEFINES%})
        set(TARGET_MODE_COPTIONS ${%TARGET_RELEASE_COPTIONS%})
        set(TARGET_MODE_LINKOPTIONS ${%TARGET_RELEASE_LINKOPTIONS%})
    endif()
endif()
#)"