R"(#"

set(EXPORT_NAME ${%EXPORT_NAME%})
set(IS_DEP ${%IS_DEP%})
set(DEPS ${%DEPS%})
set(UNIQUE ${%UNIQUE%})
set(TEST_MAIN_FILES ${%TEST_MAIN_FILES%})
set(TEST_OUT_DIR ${%TEST_OUT_DIR%})
set(EXAMPLE_MAIN_FILES ${%EXAMPLE_MAIN_FILES%})
set(EXAMPLE_OUT_DIR ${%EXAMPLE_OUT_DIR%})
set(INC ${%INC%})
set(EXPORT_INC ${%EXPORT_INC%})
set(SOURCES ${%SOURCES%})

${%FOR_GEN%}
${%FOR_MODE%}
${%FOR_TESTS%}
${%FOR_EXAMPLES%}

set(INCLUDE_DIRS ${M_INCLUDE_DIRS} ${MODE_INCLUDE_DIRS} ${GEN_INCLUDE_DIRS} ${GEN_MODE_INCLUDE_DIRS} ${EXPORT_INC})
set(LIB_DIRS ${M_LIB_DIRS} ${MODE_LIB_DIRS} ${GEN_LIB_DIRS} ${GEN_MODE_LIB_DIRS})
set(LIBS ${M_LIBS} ${MODE_LIBS} ${GEN_LIBS} ${GEN_MODE_LIBS} ${DEPS})
set(DEFINES ${M_DEFINES} ${MODE_DEFINES} ${GEN_DEFINES} ${GEN_MODE_DEFINES})
set(COPTIONS ${M_COPTIONS} ${MODE_COPTIONS} ${GEN_COPTIONS} ${GEN_MODE_COPTIONS})
set(LINKOPTIONS ${M_LINKOPTIONS} ${MODE_LINKOPTIONS} ${GEN_LINKOPTIONS} ${GEN_MODE_LINKOPTIONS})

add_library(${EXPORT_NAME} STATIC ${SOURCES})
target_include_directories(${EXPORT_NAME} PUBLIC ${INCLUDE_DIRS})
target_include_directories(${EXPORT_NAME} PRIVATE ${INC})
target_link_directories(${EXPORT_NAME} PUBLIC ${LIB_DIRS})
target_link_libraries(${EXPORT_NAME} PUBLIC ${LIBS})
target_compile_definitions(${EXPORT_NAME} PUBLIC ${DEFINES})
target_compile_options(${EXPORT_NAME} PUBLIC ${COPTIONS})
target_link_options(${EXPORT_NAME} PUBLIC ${LINKOPTIONS})

if(NOT ${IS_DEP})
    foreach(TEST_MAIN_FILE ${TEST_MAIN_FILES})
        get_filename_component(TEST_NAME ${TEST_MAIN_FILE} NAME_WE)
        set(UNIQUE_NAME "test_${TEST_NAME}_${UNIQUE}")
        add_executable(${UNIQUE_NAME} ${TEST_MAIN_FILE})
        target_include_directories(${UNIQUE_NAME} PRIVATE ${TEST_INCLUDE_DIRS} ${TEST_MODE_INCLUDE_DIRS})
        target_link_libraries(${UNIQUE_NAME} PRIVATE ${EXPORT_NAME} ${TEST_LIBS} ${TEST_MODE_LIBS})
        target_compile_definitions(${UNIQUE_NAME} PRIVATE ${TEST_DEFINES} ${TEST_MODE_DEFINES})
        target_compile_options(${UNIQUE_NAME} PRIVATE ${TEST_COPTIONS} ${TEST_MODE_COPTIONS})
        target_link_options(${UNIQUE_NAME} PRIVATE ${TEST_LINKOPTIONS} ${TEST_MODE_LINKOPTIONS})
        target_link_directories(${UNIQUE_NAME} PRIVATE ${TEST_LIB_DIRS} ${TEST_MODE_LIB_DIRS})
        set_target_properties(${UNIQUE_NAME} PROPERTIES
            OUTPUT_NAME ${TEST_NAME}
            RUNTIME_OUTPUT_DIRECTORY ${TEST_OUT_DIR})
    endforeach(TEST_MAIN_FILE ${TEST_MAIN_FILES})
    
    foreach(EXAMPLE_MAIN_FILE ${EXAMPLE_MAIN_FILES})
        get_filename_component(EXAMPLE_NAME ${EXAMPLE_MAIN_FILE} NAME_WE)
        set(UNIQUE_NAME "example_${EXAMPLE_NAME}_${UNIQUE}")
        add_executable(${UNIQUE_NAME} ${EXAMPLE_MAIN_FILE})
        target_include_directories(${UNIQUE_NAME} PRIVATE ${EXAMPLE_INCLUDE_DIRS} ${EXAMPLE_MODE_INCLUDE_DIRS})
        target_link_libraries(${UNIQUE_NAME} PRIVATE ${EXPORT_NAME} ${EXAMPLE_LIBS} ${EXAMPLE_MODE_LIBS})
        target_compile_definitions(${UNIQUE_NAME} PRIVATE ${EXAMPLE_DEFINES} ${EXAMPLE_MODE_DEFINES})
        target_compile_options(${UNIQUE_NAME} PRIVATE ${EXAMPLE_COPTIONS} ${EXAMPLE_MODE_COPTIONS})
        target_link_options(${UNIQUE_NAME} PRIVATE ${EXAMPLE_LINKOPTIONS} ${EXAMPLE_MODE_LINKOPTIONS})
        target_link_directories(${UNIQUE_NAME} PRIVATE ${EXAMPLE_LIB_DIRS} ${EXAMPLE_MODE_LIB_DIRS})
        set_target_properties(${UNIQUE_NAME} PROPERTIES
            OUTPUT_NAME ${EXAMPLE_NAME}
            RUNTIME_OUTPUT_DIRECTORY ${EXAMPLE_OUT_DIR})
    endforeach(EXAMPLE_MAIN_FILE ${EXAMPLE_MAIN_FILES})
endif()
#)"