# All configurations of builder plugin 'binary'.
[project]
name = "<project_name>" # required
# The name of the project.
type = "<type>" # required
# The type of the project.
version = "1.0.0" # required
# The version of the project.
license = "MIT"
# The license of the project.

[build]
generator = "MinGW Makefiles"
# Specify a fixed generator.
# Only valid when the current project is not a dependency.
jobs = 0
# Specify the number of threads involved in the build, default is 1.
# If specified as zero, the number of CPU cores of the device will be used.
stdc = 17
# Specify the C language standard.
stdcxx = 20
# Specify the C++ language standard.
features = ["feat1", "feat2"]
# Specify the feature to enable when the current project is not a dependency.

# For the sake of simplicity, tables with the following fields are referred to as 'Target Table'.
# The '[build]' here is a Target Table.

sources = ["src/a.cpp", "src/b.c"]
# Specify additional source files.
# This option specifies source files outside the src directory,
# and files in the src directory will be automatically searched and added.
defines = ["DEBUG"]
# Specify the global macro definition.
includes = ["include"]
# Specify the global header file search path.
link_dirs = ["dir"]
# Specify the global library search path.
link_libs = ["lib"]
# Specify additional link libraries.
compile_options = ["-Wall", "-Wextra"]
# Specify additional compile options.
link_options = ["-static"]
# Specify additional link options.
complier_features = ["cxx_std_17"]
# Specify specific compiler features.

[build.export]
compile_commands = ""
# If this configuration item exists, then during the build process,
# CMake will generate a compile_commands.json file.
# This configuration item specifies the location of the generated file.
# If it is "", it will be generated in the default location.

[features]
# Specify the dependency relationships between specified features.
feat1 = ["feat2", "feat3"]

[dependecies]
# Specify the dependencies of the project.
name = { url = "", path = "", version = "" }
# url&version OR path[&version]

# The following tables are all Target Tables and do not contain any other fields.
[build.debug]
[build.release]
[tests]
[tests.debug]
[tests.release]
[generator."<Gen>"]
[generator."<Gen>".debug]
[generator."<Gen>".release]
[feature."<feat>"]
[feature."<feat>".debug]
[feature."<feat>".release]
[target."<platform>"]
[target."<platform>".debug]
[target."<platform>".release]

# Only for type 'static','shared' and 'interface' projects.
[example]
[example.debug]
[example.release]