
[project]
name = "Project Name" # Required
# Project name.
# It can only be composed of uppercase and lowercase letters, numbers, and underscores.
version = "0.1.0" # Required
# Project version.
# Used to indicate the version number of the project.
type = "binary" # Required
# Project type.
# Used to indicate which builder plugin should be called when the project executes other commands.
# It is the same as the --type parameter specified by the `new` sub command.

[build]
generator = "MinGW Makefiles"
# Specify the generator used by CMake
# This option is used to control the toolchain called by CMake
# By default, Visual Studio 17 2022 (Windows) Unix Makefiles (Linux) are used
# Please refer to the CMake documentation for other options
jobs = 0
# Specify the number of threads involved in the build, default is 1.
# If specified as zero, the number of CPU cores of the device will be used.
features = ["feat1", "feat2"]
# Specify the feature to enable when the current project is not a dependency.
languages = ["C", "CXX"]
# Specify the programming language to be enabled.

[build.export]
compile_commands = "compile_commands.json"
# If this configuration item exists, then during the build process,
# CMake will generate a compile_commands.json file.
# This configuration item specifies the location of the generated file.
# This option is only valid for generators of the Makefile and Nijia categories.

[features]
# Specify the dependency relationships between features.
feat1 = ["feat2", "feat3"]

[dependencies]
name = { path = "path/to/package", version = "1.0.0", url="https://github.com/user/repo", features = ["feature1", "feature2"], optional = ["feat1", "feat2"] }
# Add dependencies
# 
# Among them:
# The `name` indicates the name of the dependency item, which is interpreted by Cup as the name referenced in the `link_ibraries` of the build target in CMake
# `path` indicates that the dependency item is a local project path
# `version` indicates the version of the dependency item
# `url` indicates the URL of the dependency item, used for downloading from a remote repository. For Github projects, shorthand `@<user>/<repo>` is allowed`
# `features` indicates the functional feature macro of a dependency item. How to explain that the functional feature macro is defined by the dependency's builder plugin
# `optional` indicates whether a dependency is necessary. If specified as [], the dependency will be ignored. If not empty, the dependency will only be introduced when the content has its corresponding characteristics.
# At least one of the configuration parameters `path` and `url` needs to be specified