# 这是一个典型的 Qt 项目配置文件
# 以 MinGW Qt6 为例
name = "qt"
version = "0.1.0"

[build]
target = "binary"
generator = "MinGW Makefiles"
stdcxx = 20

[build.release]
options = { link = ["-mwindows"] }

[dependencies]
Qt6 = { features = ["AUTOMOC", "AUTORCC", "AUTOUIC", "Core", "Gui", "Widgets"] }
