# All configurations of builder plugin 'binary'.
[project]
name = "project_name" # required
# The name of the project.
type = "static" # required
# The type of the project.
version = "1.0.0" # required
# The version of the project.
license = "MIT"
# The license of the project.

[build]
generator = "MinGW Makefiles"
# Specify a fixed generator.
# Only valid when the current project is not a dependency.
jobs = 0
# Specify the number of threads involved in the build, default is 1.
# If specified as zero, the number of CPU cores of the device will be used.
stdc = 17
# Specify the C language standard.
stdcxx = 20
# Specify the C++ language standard.
features = ["feat1", "feat2"]
# Specify the feature to enable when the current project is not a dependency.

defines = ["DEBUG"]
# Specify the global macro definition.
includes = ["include"]
# Specify the global header file search path.
link_dirs = ["dir"]
# Specify the global library search path.
link_libs = ["lib"]
# Specify additional link libraries.
compile_options = ["-Wall", "-Wextra"]
# Specify additional compile options.
link_options = ["-static"]
# Specify additional link options.

[build.export]
compile_commands = ""
# If this configuration item exists, then during the build process,
# CMake will generate a compile_commands.json file.
# This configuration item specifies the location of the generated file.
# If it is "", it will be generated in the default location.

[build.debug]
# They are the same as the configuration items under [build], but only effective in debug mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[build.release]
# They are the same as the configuration items under [build], but only effective in release mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[features]
# Specify the dependency relationships between specified features.
feat1 = ["feat2", "feat3"]

[dependecies]
# Specify the dependencies of the project.
name = { url = "", path = "", version = "" }

[tests]
# They are the same as the configuration items under [build], 
# but only effective for the contents in the /tests directory.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[tests.debug]
# They are the same as the configuration items under [tests], but only effective in debug mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[tests.release]
# They are the same as the configuration items under [tests], but only effective in release mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[examples]
# They are the same as the configuration items under [build], 
# but only effective for the contents in the /examples directory.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[examples.debug]
# They are the same as the configuration items under [examples], but only effective in debug mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[examples.release]
# They are the same as the configuration items under [examples], but only effective in release mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[generator."<Gen>"]
# They are the same as the configuration items under [build],
# but only take effect when the CMake generator is consistent with "<GEN>".
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[generator."<Gen>".debug]
# They are the same as the configuration items under [generator."<Gen>"], but only effective in debug mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[generator."<Gen>".release]
# They are the same as the configuration items under [generator."<Gen>"], but only effective in release mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[feature."<feat>"]
# They are the same as the configuration items under [build],
# but only take effect when the features contained in "<feat>" are enabled.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[feature."<feat>".debug]
# They are the same as the configuration items under [feature."<feat>"], but only effective in debug mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]

[feature."<feat>".release]
# They are the same as the configuration items under [feature."<feat>"], but only effective in release mode.
defines = ["DEBUG"]
includes = ["include"]
link_dirs = ["dir"]
link_libs = ["lib"]
compile_options = ["-Wall", "-Wextra"]
link_options = ["-static"]