# 这是一个典型的嵌入式项目配置文件
# 以 STM32F103C8T6 为例
name = "demo"
version = "0.1.0"

[build]
target = "binary"
generator = "MinGW Makefiles"
system = { name = "Generic", processor = "arm" }
options = { compile = [
    "-mcpu=cortex-m3",
    "-Wall -Wextra -Wpedantic -fdata-sections -ffunction-sections",
    # "-fno-rtti -fno-exceptions -fno-threadsafe-statics", 如果需要构建 C++ 目标，则添加此项
], link = [
    "-mcpu=cortex-m3",
    "-T path/to/STM32F103XX_FLASH.ld",
    "--specs=nano.specs",
    "-Wl,-Map=demo.map -Wl,--gc-sections",
    "-Wl,--start-group -lc -lm -Wl,--end-group",
    "-Wl,--print-memory-usage",
] }
suffix = ".elf"

[build.toolchain]
cc = "arm-none-eabi-gcc"
cxx = "arm-none-eabi-g++"
asm = "arm-none-eabi-gcc"
ld = "arm-none-eabi-g++"
