R"(#"

set(EXPORT_NAME ${%EXPORT_NAME%})
set(UNIQUE_SUFFIX ${%UNIQUE_SUFFIX%})
set(INCLUDE_DIR ${%INCLUDE_DIR%})
set(LINK_DIRS ${%LINK_DIRS%})
set(LINK_LIBS ${%LINK_LIBS%})
set(COPTIONS ${%COPTIONS%})
set(LOPTIONS ${%LOPTIONS%})
set(DEFINES ${%DEFINES%})
set(IS_DEP ${%IS_DEP%})
set(TEST_FILES ${%TEST_FILES%})
set(TEST_DEFINES ${%TEST_DEFINES%})
set(TEST_INCLUDE ${%TEST_INCLUDE%})
set(EXAMPLE_FILES ${%EXAMPLE_FILES%})
set(EXAMPLE_DEFINES ${%EXAMPLE_DEFINES%})
set(EXAMPLE_INCLUDE ${%EXAMPLE_INCLUDE%})
set(TEST_OUT_DIR ${%TEST_OUT_DIR%})
set(EXAMPLE_OUT_DIR ${%EXAMPLE_OUT_DIR%})

add_library(${EXPORT_NAME} INTERFACE)
target_include_directories(${EXPORT_NAME} INTERFACE ${INCLUDE_DIR})
target_compile_definitions(${EXPORT_NAME} INTERFACE ${DEFINES})
target_compile_options(${EXPORT_NAME} INTERFACE ${COPTIONS})
target_link_directories(${EXPORT_NAME} INTERFACE ${LINK_DIRS})
target_link_libraries(${EXPORT_NAME} INTERFACE ${LINK_LIBS})
target_compile_options(${EXPORT_NAME} INTERFACE ${LOPTIONS})

if(NOT ${IS_DEP})
    foreach(TEST_FILE ${TEST_FILES})
        get_filename_component(FILE_NAME ${TEST_FILE} NAME_WLE)
        set(UNIQUE "test_${EXPORT_NAME}_${FILE_NAME}_${UNIQUE_SUFFIX}")
        add_executable(${UNIQUE} ${TEST_FILE})
        target_include_directories(${UNIQUE} PRIVATE ${TEST_INCLUDE})
        target_compile_definitions(${UNIQUE} PRIVATE ${TEST_DEFINES})
        target_link_libraries(${UNIQUE} PRIVATE ${EXPORT_NAME})
        set_target_properties(${UNIQUE} PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY ${TEST_OUT_DIR}
            OUTPUT_NAME ${FILE_NAME})
        unset(UNIQUE)
    endforeach(TEST_FILE ${TEST_FILES})
    
    foreach(EXAMPLE_FILE ${EXAMPLE_FILES})
        get_filename_component(FILE_NAME ${EXAMPLE_FILE} NAME_WLE)
        set(UNIQUE "example_${EXPORT_NAME}_${FILE_NAME}_${UNIQUE_SUFFIX}")
        add_executable(${UNIQUE} ${EXAMPLE_FILE})
        target_include_directories(${UNIQUE} PRIVATE ${EXAMPLE_INCLUDE})
        target_compile_definitions(${UNIQUE} PRIVATE ${EXAMPLE_DEFINES})
        target_link_libraries(${UNIQUE} PRIVATE ${EXPORT_NAME})
        set_target_properties(${UNIQUE} PROPERTIES
            RUNTIME_OUTPUT_DIRECTORY ${EXAMPLE_OUT_DIR}
            OUTPUT_NAME ${FILE_NAME})
        unset(UNIQUE)
    endforeach(EXAMPLE_FILE ${EXAMPLE_FILES})
endif(NOT ${IS_DEP})

unset(EXPORT_NAME)
unset(INCLUDE_DIR)
unset(LINK_DIRS)
unset(LINK_LIBS)
unset(COPTIONS)
unset(LOPTIONS)
unset(DEFINES)
unset(IS_DEP)
unset(TEST_FILES)
unset(TEST_DEFINES)
unset(TEST_INCLUDE)
unset(EXAMPLE_FILES)
unset(EXAMPLE_DEFINES)
unset(EXAMPLE_INCLUDE)
unset(TEST_OUT_DIR)
unset(EXAMPLE_OUT_DIR)
#)"